# This is a basic workflow to help you get started with Actions

name: Draft a release and update version number in docs.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
    inputs:
      tagname:
        description: The tag name of the new release.
        required: true
        type: string

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  draft-release:
    runs-on: ubuntu-latest
    name: Draft the release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine old tag name
        id: tag
        run: |
          git fetch --tags
          echo 'old_tag='"$(git describe HEAD --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: List update
        id: assets
        if: env.old_tag
        run: |
          sed -i -e 's/${{ env.old_tag }}/${{ inputs.tagname }}/g' README.md

      - name: Commit to master and push
        if: env.old_tag
        run: |
          email=$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com
          name=$GITHUB_ACTOR
          msg='Bump version from `${{ env.old_tag }}` to `${{ inputs.tagname }}`'
          git config user.name $name
          git config user.email $email
          git commit -am "$msg"
          git push
          echo 'hash='"$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create release with assets
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          tag_name: ${{ github.event.inputs.tagname }}
          target_commitish: ${{ env.hash }}
          draft: true
          # name: Latest release ${{ github.event.inputs.tagname }}
          generate_release_notes: true
